spring:
    application:
        name: ai-assistant
    ai:
        openai:
            chat:
                options:
                    model: gpt-4o
            api-key: ${OPENAI_API_KEY:} # Use a variável de ambiente OPENAI_API_KEY ou deixe vazia para testes locais